name: security - gitleaks
on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main"]
permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install gitleaks
        shell: bash
        run: |
          set -euxo pipefail
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install_gitleaks.sh \
            | sh -s -- -b ./bin
          ./bin/gitleaks version

      - name: Run gitleaks
        shell: bash
        run: |
          set -euxo pipefail
          ./bin/gitleaks detect --redact --exit-code 1 --config tools/gitleaks/config.toml
