name: security - gitleaks
on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main"]
permissions:
  contents: read
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | sh -s -- -b ./
          echo "$PWD" >> $GITHUB_PATH
      - name: Run gitleaks
        run: |
          ./gitleaks detect --redact --exit-code 1 --config tools/gitleaks/config.toml